<?php

namespace whikloj\archivematicaPhp\Storage\Spaces;

/**
 * A Dataverse space type.
 * @author Jared Whiklo
 * @since 0.0.1
 */
class Dataverse extends AbstractSpaceType
{
    protected $space_name = "Dataverse";

    protected $space_type_code = "DV";

    protected $required_fields = [
        "path", // the absolute path to the Space on the local filesystem.
        "staging_path", // the absolute path to a staging area. Must be UNIX filesystem compatible and preferably will
                        // be located on the same filesystem as the path.
        "host", // Hostname or IP address of the Dataverse instance, e.g. test.dataverse.org
        "api_key", // the key generated by Dataverse for a specific user account
        "agent_name", // a string that will be used in Archivematica METS file to identify this Dataverse instance as
                        // a PREMIS agent, e.g. My Institution's Dataverse Instance.
        "agent_type", // a string that will be used in Archivematica METS file to identify the type of PREMIS agent
                        // named above, e.g. organization.
        "agent_identifier", // a string that will be used as an identifier in the Archivematica METS file to uniquely
                            // identify the PREMIS agent named above.
    ];
}
