<?php

namespace whikloj\archivematicaPhp\Storage\Spaces;

/**
 * Amazon S3 space type
 * @author Jared Whiklo
 * @since 0.0.1
 */
class S3 extends AbstractSpaceType
{
    protected $space_name = "Amazon S3";

    protected $space_type_code = "S3";

    protected $required_fields = [

        "path", // the absolute path to the Space on the local filesystem.
        "staging_path", // the absolute path to a staging area. Must be UNIX filesystem compatible
                        // and preferably will be located on the same filesystem as the path.
        "endpoint_url", // the URL of the S3 endpoint, e.g. https://s3.amazonaws.com.
        "region", // the region that the S3 instance uses, e.g. us-east-2.
    ];

    protected $optional_fields = [
        "size", // the maximum size allowed for this space. Set to 0 or leave blank for unlimited.
        "access_key_id", // to authenticate: the public key generated by S3. Not required: see below
        "secret_access_key", // to authenticate with: the secret key generated by S3. Not required: see below
        "bucket", // the name of the designated S3 Bucket. (optional). see below
    ];
    /*
     * Field notes:
     *
     * Authentication: When Access Key ID and Secret Access Key are configured, the Storage Service will attempt
     *  to authenticate with those details. When these values are not configured, the Storage Service will attempt
     *  to use authentication details provided by the AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY environment
     *  variables.
     *
     * Bucket: When the bucket name is configured, that bucket will be used. Otherwise, the ID of the space will be
     *  used instead. In either case the bucket will be automatically created if necessary, and if the AWS user has
     *  permissions to do so.
     */
}
